name: push and build the app
on: 
  push:
    branches: [ master ]
  

jobs: 

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./packages/db/.env

      - name: building the frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: vishu0210/frontend-backend:${{github.sha}}
      
      - name: build and push http-backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.http-backend
          push: true
          tags: vishu0210/http-backend:${{github.sha}}

      - name: build and push ws-backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws-backend
          push: true
          tags: vishu0210/ws-backend:${{github.sha}}
      
      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.240.24.6 >> ~/.ssh/known_hosts
          
      # - name: Debug SSH key
      #   run: |
      #     # Check if the key looks valid (shouldn't show full key in logs)
      #     wc -l ~/.ssh/id_rsa
      #     head -n 1 ~/.ssh/id_rsa
          
      - name: Connect and create directory
        run: |
          ssh -v ubuntu@103.240.24.6

      - name: transfer file via scp to my vm
        run: 
      
      